cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('', views.cart_detail, name='cart_detail')
]

cupons/urls.py
from django.urls import path
from . import views


app_name = 'cupon'
urlpatterns = [
    path('apply', views.cupon_apply, name='apply')
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf')
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('<category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug>/', views.product_detail, name='product_detail'),
    path('', views.product_list, name='product_list')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from cupons.forms import CuponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'update': True})
    cupon_apply_form = CuponApplyForm()
    return render(request, 'cart/detail.html',
                  {'cart': cart, 'cupon_apply_form': cupon_apply_form})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% block tiile %}
    Ваша корзина
{% endblock %}
{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table table class="table-cart" border="1px">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" class="img-responsive" width="200" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url 'cart:cart_add' product.id %}" method="post" class="add">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    {% csrf_token %}
                    <input type="submit" value="Обновить">
                </form>
            </td>
            <td><a href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        {% if cart.cupon %}
          <tr class="subtotal">
            <td>Сумма без скидки</td>
            <td colspan="4"></td>
            <td>{{ cart.get_total_price }}</td>
          </tr>
          <tr>
            <td>
              "{{ cart.cupon.code }}" купон на ({{ cart.cupon.discount }} % ниже)
            </td>
            <td colspan="4"></td>
            <td class="num discount">- {{ cart.get_discount|floatformat:"2" }} руб.</td>
          </tr>
        {% endif %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price_after_discount }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p>Применить купон</p>
  <form action="{% url "cupon:apply" %}" method="post" class="add">
    {% csrf_token %}
    {{ cupon_apply_form }}
    <input type="submit" value="Обновить">
  </form>
  <p class="text-right">
    <a href="{% url "shop:product_list"%}" class="btn">Продолжить Шопинг</a>
    <a href="{% url 'orders:order_create' %}" class="btn">Оформить заказ</a>
  </p>
{% endblock %}